sudo: false
language: scala
scala:
  - 2.11.12
  - 2.12.11
  - 2.13.2
jdk:
  - openjdk11
env:
  - JSDOM_VERSION=16.2.2 SCALAJS_VERSION=
  - JSDOM_VERSION=16.2.2 SCALAJS_VERSION=0.6.32
install:
  # We need a recent version of Node.js for jsdom
  - nvm install 12
  - nvm use 12
  - node --version
  # Of course we need jsdom
  - npm install jsdom@$JSDOM_VERSION
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-env-jsdom-nodejs/test scalajs-env-jsdom-nodejs/doc
  - sbt ++$TRAVIS_SCALA_VERSION test-project/run test-project/test
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete
  - find $HOME/.cache/coursier -name "*.lock"               -print -delete
